auditor = "mongo"
connection_string = "mongodb+srv://kubelet:qr4zx4YdzmwPuLmx@kubernetes-honeypot-audit-spuml.gcp.mongodb.net/test?retryWrites=true&w=majority"
pod_store_path = "/Users/eprokop/repos/kubernetes-honeypot/kubelet/pods.json"

[capacity]
cpu = "8"
memory = "16G"
pods = "256"