apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: None
    users: ["minikube", "system:serviceaccount:kube-system:coredns"]
  - level: Request
    resources:
      - group: ""
        resources: ["pods", "deployments", "secrets", "services"]
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
      - "/*"
  - level: Request
    nonResourceURLs:
      - "/*"
  # A catch-all rule to not log all other requests
  - level: None
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"