apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: None
    users: ["minikube", "system:serviceaccount:kube-system:coredns"]
  - level: None
    userGroups: ["system:authenticated"]
  - level: Request
    resources:
      - group: ""
        resources: ["*"]
    nonResourceURLs:
      - "/*"
  # - level: None
  #   # Long-running requests like watches that fall under this rule will not
  #   # generate an audit event in RequestReceived.
  #   omitStages:
  #     - "RequestReceived"